### ISSUE TITLE
Demo does not work!

### ISSUE THREAD

**Issue by mariomann** [inspectIT/inspectit-ocelot#1264]
The inspectIT ocelot demo does not work out of the box and it's also mixed up.

1. There are different demo archives with different docker-compose files. Please check [demo-archive](https://github.com/inspectIT/inspectit-ocelot/releases/latest) and the directory in the master branch.
2. The demo in the demo-archive reference to a docker image wich only work on MacOS operating systems. (Docker-Image: inspectit/spring-petclinic-config-server)`Error starting command: java - fork/exec /opt/java/openjdk/bin/java: exec format error` This error happens because the build was done on a MacOS operating system. I can't start this image on Ubuntu operating system.
3. The demo in the master branch directory referenced to a docker image which does not exist. (Docker-Image: inspectit/inspectit-ocelot-eum-server)

Please fix it. To prevent this error please use a pipeline like `Github Actions` in future to build artefacts.

**Comment by Mahir-Isikli** [comment]
Hi, 
this is a problem that will be fixed in the coming days. Until then the following workaround works:

- clone our PetClinic Repo https://github.com/inspectIT/spring-petclinic-microservices
- build the Docker images yourself with the command `./mvnw clean install -P buildDocker -DskipTests`

That should build the PetClinic microservices for the linux/amd64 architecture and let you start the images.
