### ISSUE TITLE
Fetching configuration via HTTP

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#199]
The agent should be able to fetch its configuration via HTTP. Have to match the configurations REST api: #196 

The HTTP configuration can be fetched after the actual agent start. The HTTP config priority is below the file-based one.

**Comment by jbadeau** [comment]
This is an interesting approach but would it not be better to use something like GRCP websocket, etc so that config updates could be pulled and pushed to the agent?

**Comment by JonasKunz** [comment]
The idea behind our planned HTTP approach is that this way the agent is not actually bound to use our configuration server as configuration source. With plain HTTP, the configuration could come from any source, e.g. a GitHub repository.
We still will realize the possibility to update the configuration on the server side and "send" it to the agent via polling.
The agent will poll the configured HTTP endpoint in a configurable interval to see, if the configuration has changed. To minimize the overhead we plan on using HTTP-caching headers, one candidate is [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since). With these headers, the configuration will only be sent from the server if it actually has changed.

**Comment by AlexanderWert** [comment]
Regarding the pull vs. push principle:

With a push principle we would need to realize authentication and authorization on agent side to prevent someone from injecting agent configurations that may cause demage of any kind through improper configuration. So it's more a question of security.

Moreover, a pull based principle allows to scale better, as it is a stateless approach rather than keeping states of the connections.

@jbadeau Do you have a concrete requirement for a push-based approach?

**Comment by jbadeau** [comment]
Ok, I just though that since opencensus is already using grcp as 1 of their context propagation strategies then it would be a good fit. Anyway I think it’s a great feature.

**Comment by jbadeau** [comment]
Yes, I see your point about security. I think polling would be suitable for production but in local or testing a connection might be a better choice due to frequency of change.

**Comment by jbadeau** [comment]
We heavily use tracing for analyzing exceptions arising from e2e tests
