### ISSUE TITLE
Add REST API for fetching connected agents

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#307]
It would be usefull to see 
* which Agents connected to the config server
* when they last polled the configuration and 
* which mapping was used for which agent

This data is accessible through a GET endpoint and a DELETE which clears the history.

**Comment by AlexanderWert** [comment]
We should add a flag to the corresponding REST endpoint that indicates, whether the status should be tracked or not. Otherwise this endpoint cannot be used for other purposes (e.g. showing the agent specific configuration in the UI).

What do you think?

**Comment by mariusoe** [comment]
The agents have dedicated endpoints for fetching their configuration which is never used by the UI - e.g. due to authentication etc.

Currently, there is only a single endpoint which is used by agents. Thus, there should not be a problem if that endpoint is tracking the agents' states.

Is that what you meant?
