### ISSUE TITLE
Handle invalid metric tags in agent

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#391]
Currently, if the agent tries to tag a metric with a tag value with is not considered as valid (see https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/tags/TagValue.java) it will throw an exception and the hook which is recording the metric will be deactivated.

This should be handled, e.g. the tag value could be set to `<invalid>`. By doing this, bad configurations are also be visible using the metrics.

**Comment by arolfes** [comment]
Hi @mariusoe ,
from my point of view there are 2 quick solutions:

inside `rocks.inspectit.ocelot.core.tags.CommonTagsManager`

a) catch exception and change value example
```java
            TagValue value = null;
            try {
                value = TagValue.create(v);
            } catch (IllegalArgumentException e) {
                log.warn("illegal tag value {} converted to <invalid>", v);
                value = TagValue.create("<invalid>");
            }
            tagContextBuilder.putLocal(key, value);
```

b) copy TagValue.isValid(String) and check the result
```java
            if (!isTagValueValid(v)) {
                log.warn("illegal tag value {} converted to <invalid>", v);
                v = "<invalid>";
            }
            
            tagContextBuilder.putLocal(key, TagValue.create(v));
.
.
.
    private static boolean isTagValueValid(String value) {
        return value.length() <= TagValue.MAX_LENGTH && StringUtils.isPrintableString(value);
    }

```

do you have another approach in mind?

i would prefer solution a) because there we are independent from "what is a valid TagValue Definition by OpenCensus" but I  don't really like to catch the IllegalArgumentException ...

what do you think?
