### ISSUE TITLE
Prevent log spam if the HTTP config is unavailable

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#406]
At the current state, the agent prints an error message for every unsuccessful connection attempt to the configured http config URL.
We should add a "failure-counter" and print only on 1,2,4,8... attempt the error message.
In addition we should print a success message on INFO-level for the first successful fetch after a failure.

**Comment by rexino** [comment]
So if i understand correctly, in class `HttpPropertySourceState` in method `fetchConfiguration` we need to count errors in connections and if the connection is made, we need to print success? Or what errors do you need to count?

**Comment by mariusoe** [comment]
Hi @rexino 
yes that is the idea here.
The current "problem" is that the agent is logging each failed configuration fetching. This means, that in case a problem exists, e.g. configuration server is not reachable, and the agent tries to fetch the configuration in a period of 30 seconds that each 30 seconds an error is logged.

The idea is that in case that happens, that we don't print every exception log in order to reduce the amount of logs. But only the 1, 2, 4, 8, ... attempt, as @JonasKunz mentioned. Obviously this has to be resettet in case the connection is succesful (which also should be logged).

**Comment by rexino** [comment]
Ok i will try it

**Comment by rexino** [comment]
1,2,4,8... should i understand this as print only every attempt that equals powers of two? Or is it just an example?

**Comment by rexino** [comment]
I am also detecting "log-spam" in current version that is in master when config is successfully fetched with message.
`INFO  94640  --- [inspectIT] [pectit-thread-1] r.i.o.c.c.p.h.HttpPropertySourceState    : HTTP Configuration has successfully been fetched.`
I suppose this "log-spam" should be solved too, yeah?
