### ISSUE TITLE
TraceTestBase is unstable and occasionally failing

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#500]
The system tests, related to the `TraceTestBase` are unstable and fail often during CI builds. See: https://circleci.com/gh/inspectIT/inspectit-ocelot/4075

This behavior causes that builds have to manually restarted in order to build without any failure.

The tests have to be refactored and fixed to prevent failing builds.

**Comment by JonasKunz** [comment]
So I presume that the root cause for the usntability is the finding I recently had a customer:
When under high CPU load and generating spans at a very fast rate, it is possible that the internal disruptor queue gets full and spans are dropped. The queue has a capacity of 8192, which is filled with metric writes, span start events and span end events. This means that if the disruptor thread did not get any CPU time after 4096 span writes, subsequent spans will be dropped.
