### ISSUE TITLE
Posibility to obfuscate data pushed to traces

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-ocelot#556]
We need a configuration property for specifying patterns that should be used for checking if data pushed to the traces should be obfuscated or not. The pattern could be applied against the property name/key, value or both. 

The obfuscation should be performed against:
* span attributes
* span name?  

The pattern definition should specify the type of the pattern. Currently we have following matcher modes (should we use the same?):
- EQUALS_FULLY
- EQUALS_FULLY_IGNORE_CASE
- STARTS_WITH
- STARTS_WITH_IGNORE_CASE
- ENDS_WITH
- ENDS_WITH_IGNORE_CASE
- CONTAINS,
- CONTAINS_IGNORE_CASE
- MATCHES

Furthermore:
- meaningful defaults should be defined
- documentation must be updated

@JonasKunz @mariusoe Would be great if you could give answers to the above questions and propose the best place in the configuration model to have the settings available. As this could be applied to metrics later on, maybe it's better to have this as more generic option.

**Comment by JonasKunz** [comment]
I would suggest not overengineering how patterns are specified. E.g. if you support RegExes, then just regex is sufficient. The moes for the scope matchers are diretly taken from bytebuddy, which does not apply here.

In addition I would suggest that there are no defaults here, because this is a niche usecase.

**Comment by mariusoe** [comment]
I agree with @JonasKunz 
I would also say that it is sufficient when we start with just using regex matcher. Or maybe two options:

* regex
* equals

In case the regex comparision will become a problem (because it may be slow), we can still split this up and implement optimized and different matcher. But for the first iteration, regex should be totally fine.

**Comment by JonasKunz** [comment]
I think just regex is fine, we can even later automatically derive "optimized" implementations based on the given regex pattern: E.g. ".*[LITERAL].*" is "contains", "[LITERAL].* is "startsWith", ".*[LITERAL]" is "endsWith".
