### ISSUE TITLE
Collect database and cache metrics (requests, throughputs...)

### ISSUE THREAD

**Issue by raybah** [inspectIT/inspectit-ocelot#559]
Hi, thanks for that project. Do you have plans to implement database and cache metrics like requests and throughputs? Or may be you've already done it? If yes - how it can be enabled? We use prometheus server and ocelot exporter by default.
Also when I enabled the agent the load was increased very much.

Ocelot agent: "1.0"
OS: "CentOS 6"
JRE - "1.8.0_92"
Spring version - "4.0.5"
Tomcat version - "7.0.35.0"

**Comment by mariusoe** [comment]
Hi @raybah 

currently, we don't have a default configuration to collect cache metrics (I assume you mean some kind of cache-data-structure?)? But you can achive this quite easily. Just create a new rule which enables tracing and assign a scope to it which matches your caching class and methods. See: https://inspectit.github.io/inspectit-ocelot/docs/instrumentation/rules#collecting-traces

For the database metrics, we currently gathering database metrics using an instrumentation targeting the JDBC interface. Thus, if you use JDBC you'll get database metrics, otherwise you have to create a new configuration which is adapted to your usecase.

What do you mean by `when I enabled the agent the load was increased very much`?

**Comment by raybah** [comment]
@mariusoe , thanks for the information. We have tomcat app installed on our server and when we restarting it with ocelot agent option, load increased gracefully and takes up all available processor resources.

**Comment by mariusoe** [comment]
Hi @raybah 

it is normal that the agent will cause some kind of overhead in CPU and memory usage. This overhead heavily depends on the configuration which is used. Thus, can you share your agent configuration?

**Comment by raybah** [comment]
The fact is that I used the default configuration. That is, I just downloaded the agent and connected it to the Java application, I didn't make any additional settings.
Agent version - 1.0
btw I just wanted to ask how can I correctly configure the agent? Need to download extra something? Apparently, I didn't find any configuration files which would be delivered with the agent package. May be I have create these files and add args to the app (https://inspectit.github.io/inspectit-ocelot/docs/configuration/external-configuration-sources#file-based-configuration)?

**Comment by AlexanderWert** [comment]
Hi @raybah
it's quite hard to say why your cpu utilization is increasing without knowing the exact system or having more information. There might be multiple reasons for this e.g. the application itself is increasing the load or something is wrong with the agent in your setup.
Regarding the configuration: there are multiple options to provide a configuration to the agent (see the link you already posted).
* provide your configuration files locally to the agent, via the file system
* use environment or system parameters containing the desired options
* fetching an HTTP endpoint providing the configuration (e.g. the Ocelot configuration server)

By default, the agent is shipped with a default configuration bundled in the agent Jar. You can find the default configuration here: https://github.com/inspectIT/inspectit-ocelot/tree/master/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config
If you need some special configuration you have to create them manually.

**Comment by mariusoe** [comment]
Ticket will be closed.
Feel free to reopen or open a new ticket if further question arise.
