### ISSUE TITLE
agent 1.3

### ISSUE THREAD

**Issue by RRadziejewski** [inspectIT/inspectit-ocelot#733]
I have a question, i've run agent with default config and i get errors like this in fille attached.
I also don't get any EJB traces, any idea how to get them ? I am attaching agent to the PID of my application instance but i don't see any EJB traces. I am attaching exceptions.log file.
Also i get weird output in jaeger ui for Database queries traces. Can you please help me or provide instruction how to get EJB traces ?
Also very good job for http traces !!
Attaching exceptions.log

[exceptions.log](https://github.com/inspectIT/inspectit-ocelot/files/4608399/exceptions.log)

**Comment by RRadziejewski** [comment]
Where is the default config for EJB traces? Is there any ?

**Comment by RRadziejewski** [comment]
Also for Database queries i get output like this 
![2020-05-11_10-55-31](https://user-images.githubusercontent.com/32438378/81543190-048d1400-9376-11ea-95f0-a70d394ceb0d.png)

Should it be like this with this $proxy indicator?

**Comment by RRadziejewski** [comment]
Also i can't map any configuration to the agents in newest ocelot-config server look at the screens
![chrome_2020-05-11_11-05-00](https://user-images.githubusercontent.com/32438378/81544146-6306c200-9377-11ea-8022-bbf3146e68c2.png)
![chrome_2020-05-11_11-05-19](https://user-images.githubusercontent.com/32438378/81544161-69953980-9377-11ea-8aad-c613a232b7be.png)

**Comment by mariusoe** [comment]
Hi @RRadziejewski 

we're glad the HTTP tracing is working :)

The attached log file looks like you are trying instrument classes which are not located inside a package but inside the default one - so no package has been defined. This is currently not supported by the agent.

Regarding your question on the JDBC/EJB output in Jaeger: yes, that's correct.
The default configuration uses the actual class name as span name. Due to the fact, that your database queries are executed by an EJB proxy object, this is actually correct. The class name of your instances is in fact `$Proxy345`.
You are able to specify the span name by yourself, but it requires an adapted configuration which does not use the class name of the current instance as span name but using a different approach for that. You can find information on setting the span name in the [documentation](https://inspectit.github.io/inspectit-ocelot/docs/instrumentation/rules#collecting-traces).

Currently, we have no ready-to-use configuration available for EJB, yet. Since we have limited development resources, we cannot provide configurations for all features and technologies, but are reliant on the community for this. However, if this is important to you, you can consider sponsoring the project so that we can implement this.

**Comment by RRadziejewski** [comment]
Hi @mariusoe 

Thanks for the help !!
So HTTP AND JDBC is working as correct but i cannot find any information on how to instrument ejb over the web. I think it will be long journey :D i will attach my config file which... do not work
maybe you can give me any feedback about it 



`inspectit:
  instrumentation:
    scopes:
      example_scope_ejb0:
        superclass:
          name: "rocks.inspectit.shared.cs.ci.sensor.method.impl.TimerSensorConfig"
          matcher-mode: "CONTAINS"
      example_scope_ejb4:
        interfaces:
          - name: "javax.ejb.MessageDriven"
            matcher-mode: EQUALS_FULLY
      example_scope_ejb1:
        interfaces:
          - name: "javax.ejb.Stateless"
            matcher-mode: EQUALS_FULLY
      example_scope_ejb2:
        interfaces:
          - name: "javax.ejb.Stateful"
            matcher-mode: EQUALS_FULLY
      example_scope_ejb3:
        interfaces:
          - name: "javax.ejb.Singleton"
            matcher-mode: EQUALS_FULLY
    rules:
      example_rule_ejb0:
        scopes:
          example_scope_ejb0: true
        tracing:
          start-span: true
      example_rule_ejb4:
        scopes:
          example_scope_ejb4: true
        tracing:
          start-span: true
      example_rule_ejb2:
        scopes:
          example_scope_ejb2: true
        tracing:
          start-span: true
      example_rule_ejb1:
        scopes:
          example_scope_ejb1: true
        tracing:
          start-span: true
      example_rule_ejb3:
        scopes:
          example_scope_ejb3: true
        tracing:
          start-span: true    `
