### ISSUE TITLE
HttpUrlConnection does not recognize target services

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#769]
Since pull-request #749 the HttpConnection instrumentation does not correctly set the target-application in the generated metrics (see system tests, e.g.: `rocks.inspectit.ocelot.instrumentation.servicegraph.HttpServiceOutMetricTest.HttpUrlConnection#testInternalCallRecording`).

In the previous mentioned test, the problem is that the generated metric doesn't contain the `target_service` tag. Considering the Wiremock output, the correlation context is correctly set, at least for the down-propagation.
If we revert the change of the mentioned pull-request and removing the `s_httpurlconnection_requestInitiators` scope from the `r_httpurlconnection_tracing_end`, `r_httpurlconnection_servicegraph_record` and `r_httpurlconnection_http_metric` rule, the `target_service` tag is set again and the test is not failing anymore.

**Comment by JonasKunz** [comment]
The root problem is that the propagation rules `r_httpurlconnection_up_propagation` and `r_httpurlconnection_down_propagation` rely that they are applied on the first `HttpUrlConnection` methods on the callstack. Since we added new methods to the other rules like `r_httpurlconnection_tracing_end` doing this check (via `s_requestInitatiors`), the propagation would never occur.
The simples solution is to remove this entry-point check from the propagation here.
The actions for the propagation set a marker on the `HttpUrlConnection`-instance in order to prevent setting the headers multiple times anyway.
