### ISSUE TITLE
Extend configuration Alert UI: Add MS Teams as an additional kapacitor handler

### ISSUE THREAD

**Issue by Patrick-Eichhorn** [inspectIT/inspectit-ocelot#932]
Offers the possibility to add a MS Team channel as an alert handler in the configuration Alert UI

**Comment by mc-chaos** [comment]
@Patrick-Eichhorn : Is this Issue closed with the latest MS Teams integration?

**Comment by mariusoe** [comment]
Hello @mc-chaos 

as I see it, this ticket could be closed, since there is now the project https://github.com/NovatecConsulting/kapacitor-ms-teams-handler to set up MS teams handlers in Kapacitor, which are then also displayed in the configuration server UI.

But I think @Patrick-Eichhorn can give more details about this.

**Comment by Patrick-Eichhorn** [comment]
Hi @mc-chaos
I will close this ticket for the above reasons (@mariusoe ). Please follow the instructions (https://github.com/NovatecConsulting/kapacitor-ms-teams-handler) to use the MS Teams kapacitor handler in the alerting UI.
