### ISSUE TITLE
Question: Basic tracing info using only Prometheus / zero conf and overhead?

### ISSUE THREAD

**Issue by bonndan** [inspectIT/inspectit-ocelot#969]
Hi,

excuse my questions if they were answered in the docs, maybe I have just missed them:

1) Is it possible to gather basic tracing data with ocelot if I only have Prometheus (no Jaeger/Zipkin etc). It would be sufficient if the data would be available in Prometheus.

2) Is it really zero-conf with Spring Boot apps? Can I use the agent with an app jar and it will record all kinds of http/tcp/younameit requests including RestTemplate and all that dirty Spring magic?

3) What about performance/memory/stability impact when I use the agent?

Thanks!

**Comment by mariusoe** [comment]
Hi @bonndan 

regarding your questions:

> 1. Is it possible to gather basic tracing data with ocelot if I only have Prometheus (no Jaeger/Zipkin etc). It would be sufficient if the data would be available in Prometheus.

It depends on what you mean by "basic tracing data". Using only Prometheus, you will not get any traces but you will get metrics which relate to tracing. E.g. you can get a call-count or response time of certain methods or functionallity. But you will not get the data representing a call hierachy, e.g. method X calls method Y.

> 2. Is it really zero-conf with Spring Boot apps? Can I use the agent with an app jar and it will record all kinds of http/tcp/younameit requests including RestTemplate and all that dirty Spring magic?

Yes, at least in part. When attaching the agent, you should get your RestTemplate communication without the need of touching the agent's configuration.
But there are also some limitations: currently we don't support every communication framework just because there are so many differnt kinds of. For example, if your looking for JMS communictation, that feature is currently not available out-of-the-box. In the near future, we'll provide additional confgurations for multiple frameworks, so users can download and use them.

> 3. What about performance/memory/stability impact when I use the agent?

Regarding stability, this should not be a problem. The agent's code will be separated from the application itself and will not affect it. An error in the agent causes the affected functionality to be disabled and thus has no effect on the application.

The question on the performance and memory overhead is hard to answer because it depends on many things like, the configuration used or the application itself and how many data is collected. It is sure that the agent causes some overhead in CPU and memory consumtion but it is not possible for us to give concrete numbers on this. CPU wise, you shouldn't see some big difference in the load. For memory, the agent needs some couples of megabyte for itself and then it uses a buffer to store the collected data before sending. The agent will not cause an out of memory if the data cannot be written to a data sink but it will drop data in that case.

**Comment by bonndan** [comment]
Thanks for the response. I'll recommend to test ocelot on the next occasion.

**Comment by mariusoe** [comment]
Awesome.
